name: odekeke
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.4
  geolocator: ^9.0.0
  location: ^4.4.0
  flutter_native_splash: ^2.2.3+1
  google_maps_flutter: ^2.1.8
  google_polyline_algorithm: ^3.1.0
  http: ^0.13.4
  english_words: ^4.0.0
  animated_text_kit: ^4.2.2

flutter_native_splash:
    image: "images/taxi_splash.png"
    color: "008000"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "images/taxi_splash.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/top_page.jpg
    - images/zikoku1.jpg
    - images/zikoku2.jpg
    - images/zikoku3.jpg
    - images/zikoku4.jpg
    - images/taxi_splash.png
    - images/top1.jpeg
    - images/top2.jpeg
    - images/top3.jpeg
    - images/bus1.jpeg
    - images/bus2.jpeg
    - images/taxi1.jpeg
    - images/taxi2.jpeg
    - images/taxi3.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
